name: stripe
command:
  bootstrap:
    usePubspecOverrides: true
packages:
  - ./**
scripts:
  analyze: melos exec -- flutter analyze
  format: melos exec -- dart format .
  get: melos exec -- flutter pub get
  unittest: 
    run: melos exec -- flutter test
    select-package:
      dir-exists:
        - test
      scope: "*interface*"


