name: flutter_stripe
description: Flutter library for Stripe.
version: 1.0.0+3
homepage: https://github.com/flutter-stripe/flutter_stripe
repository: https://github.com/flutter-stripe/flutter_stripe/tree/main/stripe

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  stripe_android:
    path: ../stripe_android
  stripe_ios: 
     path: ../stripe_ios
  stripe_platform_interface:
    path: ../stripe_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
    




