/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.reactnativestripesdk.compat.react.viewmanagers;

import android.view.View;

import androidx.annotation.Nullable;

import com.reactnativestripesdk.compat.react.bridge.Dynamic;
import com.reactnativestripesdk.compat.react.bridge.ReadableArray;
import com.reactnativestripesdk.compat.react.uimanager.ViewManagerWithGeneratedInterface;

public interface AddressSheetViewManagerInterface<T extends View> extends ViewManagerWithGeneratedInterface {
  void setVisible(T view, boolean value);
  void setPresentationStyle(T view, @Nullable String value);
  void setAnimationStyle(T view, @Nullable String value);
  void setAppearance(T view, Dynamic value);
  void setDefaultValues(T view, Dynamic value);
  void setAdditionalFields(T view, Dynamic value);
  void setAllowedCountries(T view, @Nullable ReadableArray value);
  void setAutocompleteCountries(T view, @Nullable ReadableArray value);
  void setPrimaryButtonTitle(T view, @Nullable String value);
  void setSheetTitle(T view, @Nullable String value);
  void setGooglePlacesApiKey(T view, @Nullable String value);
}
