/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.reactnativestripesdk.compat.react.viewmanagers;

import android.view.View;

import androidx.annotation.Nullable;

import com.reactnativestripesdk.compat.react.bridge.Dynamic;
import com.reactnativestripesdk.compat.react.uimanager.ViewManagerWithGeneratedInterface;

public interface AuBECSDebitFormManagerInterface<T extends View> extends ViewManagerWithGeneratedInterface {
  void setCompanyName(T view, @Nullable String value);
  void setFormStyle(T view, Dynamic value);
}
