/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.reactnativestripesdk.compat.react.viewmanagers;

import android.view.View;

import androidx.annotation.Nullable;

import com.reactnativestripesdk.compat.react.bridge.DynamicFromObject;
import com.reactnativestripesdk.compat.react.bridge.ReadableArray;
import com.reactnativestripesdk.compat.react.uimanager.BaseViewManager;
import com.reactnativestripesdk.compat.react.uimanager.BaseViewManagerDelegate;
import com.reactnativestripesdk.compat.react.uimanager.LayoutShadowNode;

public class EmbeddedPaymentElementViewManagerDelegate<T extends View, U extends BaseViewManager<T, ? extends LayoutShadowNode> & EmbeddedPaymentElementViewManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public EmbeddedPaymentElementViewManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "configuration":
        mViewManager.setConfiguration(view, new DynamicFromObject(value));
        break;
      case "intentConfiguration":
        mViewManager.setIntentConfiguration(view, new DynamicFromObject(value));
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }

  @Override
  public void receiveCommand(T view, String commandName, @Nullable ReadableArray args) {
    switch (commandName) {
      case "confirm":
        mViewManager.confirm(view);
        break;
      case "clearPaymentOption":
        mViewManager.clearPaymentOption(view);
        break;
    }
  }
}
