/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.reactnativestripesdk.compat.react.viewmanagers;

import android.view.View;

import com.reactnativestripesdk.compat.react.bridge.Dynamic;
import com.reactnativestripesdk.compat.react.uimanager.ViewManagerWithGeneratedInterface;

public interface EmbeddedPaymentElementViewManagerInterface<T extends View> extends ViewManagerWithGeneratedInterface {
  void setConfiguration(T view, Dynamic value);
  void setIntentConfiguration(T view, Dynamic value);
  void confirm(T view);
  void clearPaymentOption(T view);
}
