name: Docs

on:
  push:
    branches-ignore:
      - master
jobs:
  readme:
    name: Typo CI (GitHub Action)
    runs-on: ubuntu-latest
    timeout-minutes: 4
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: root readme matches stripe matches
        run: ./.github/workflows/scripts/compare_readme.sh
